# Light weight base image
FROM python:3-alpine

# Maintainer
MAINTAINER mann.dhiman@gmail.com

# Copy the current directory content into the container at /Package
COPY . /Package

# Install package requirements
RUN apk add --no-cache musl-dev linux-headers gcc g++ freetype-dev libpng-dev openblas-dev gfortran\
    && if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi \
    && if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi 

RUN pip install --no-cache -r /Package/requirements.txt


# Set the working directory to /Package
WORKDIR /Package

# Make port 5000 available to the world outside the container
EXPOSE 5000

# Entry point in the container for present example -
# Launch Flask web server
ENTRYPOINT ["python"]
CMD ["app/server.py"]
